import React from 'react'
import { assets } from '../assets/assets'
import '../Components/Home.css'
import { Navigate, useNavigate } from 'react-router-dom'

export const Header = () => {
  const navigate = useNavigate();
  return (
    <div>
      <div className='text-center justify-content-center d-flex row mt-5 mx-auto' style={{ width: "100%" }}>
      <p
  className="p-1 fw-bold inline-flex rounded-1"
  style={{ background: "linear-gradient(to left,rgb(224, 235, 247),rgb(73, 147, 226) 80%)",
    color: "darkblack",
    width: "200px",
  }}
>
  Welcome Buddy 
  <img src={assets.star_icon} alt="star icon" style={{ marginLeft: "10px" }} />
</p>

        <p className=' pb-2 fw-bold' style={{ fontSize: "35px", color: "white" }} >Make Your <span style={{ color: "rgb(0,122,255)" }}>Imagination</span> into Real on <span style={{ color: "rgb(0,122,255)" }}>Imagenation</span></p>
        <div className='text-center justify-content-center d-flex row'>
          <p className='pb-3 m' style={{ width: "70%", color: "white" }}>"Bring your ideas to life with our AI Image Generator!
            Create unique, high-quality visuals in seconds.
            Easy to use and customizable for any style.
            Ideal for artists, designers, and creators alike!</p>
        </div>
        <button style={{ backgroundColor: "black", color: "white", width: "300px" }} className='promtBtn mb-3 rounded-5 ' onClick={()=>navigate('/generate-image')}>Generate your prompt <img style={{ height: "25px", width: "30px" }} src={assets.star_group} alt="" /></button>
      </div>
     
      <div
  className="d-flex pt-4 justify-content-center gap-1 sliding-container"
>
  
  {Array(6)
    .fill("")
    .map((_, index) => (
      <img
        height={80}
        width={70}
        src={
          index % 2 === 0
            ? assets.sample_img_1
            : assets.sample_img_2
        }
        key={index}
        alt=""
        className="sliding-image"
        style={{ animationDelay: `${index * 0.3}s` }} // Staggered animation
      />
    ))}
</div>
<div className=' text-white text-center'>
      <p >Images Generated By Imagenation</p>
      </div>

    </div>
  )
}
